# Generated by Django 5.2 on 2025-05-28 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Microcontroller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('identifier', models.CharField(max_length=100, unique=True)),
                ('installed_on', models.DateTimeField(auto_now_add=True)),
                ('bed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='microcontroller', to='live_data.bed')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('bed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='live_data.bed')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='live_data.ward')),
            ],
        ),
        migrations.CreateModel(
            name='PatientVitalReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('oxygen_saturation', models.FloatField()),
                ('body_temperature', models.FloatField()),
                ('heartrate', models.IntegerField()),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_vital_reading', to='live_data.patient')),
            ],
        ),
        migrations.AddField(
            model_name='bed',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='live_data.ward'),
        ),
        migrations.CreateModel(
            name='WardReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('microcontroller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward_readings', to='live_data.microcontroller')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward_conditions', to='live_data.ward')),
            ],
        ),
        migrations.AddConstraint(
            model_name='bed',
            constraint=models.UniqueConstraint(fields=('ward', 'bed_number'), name='unique_bed_per_ward'),
        ),
    ]
