# Generated by Django 5.2 on 2025-05-18 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wardreading',
            name='air_quality',
        ),
        migrations.RemoveField(
            model_name='wardreading',
            name='noise_level',
        ),
    ]
