# Generated by Django 5.2 on 2025-05-18 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_data', '0002_remove_wardreading_air_quality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientvitalreading',
            name='microcontroller',
        ),
        migrations.AddField(
            model_name='patientvitalreading',
            name='patient',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patient_vital_reading', to='live_data.patient'),
            preserve_default=False,
        ),
    ]
