# Generated by Django 5.2 on 2025-05-18 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_data', '0003_remove_patientvitalreading_microcontroller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardreading',
            name='microcontroller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ward_readings', to='live_data.microcontroller'),
            preserve_default=False,
        ),
    ]
