# Generated by Django 5.2 on 2025-05-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_data', '0004_wardreading_microcontroller'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bed',
            constraint=models.UniqueConstraint(fields=('ward', 'bed_number'), name='unique_bed_per_ward'),
        ),
    ]
